#!/usr/bin/env python3

print('[APRENDIZAJE_03]')
print()
print('LEY_06_PROTEGER_ATENCION')
print()
print('Principio:')
print('La atencion de la colonia es su recurso mas escaso.')
print('Lo que no merece atencion no debe recibirla en absoluto.')
print()
print('Zona de solapamiento 0.70-0.84:')
print('Dos leyes activas. El tipo de ataque decide.')
print()
print('Tabla de decision:')
print()
print('  Tipo de ataque      | Ley activa       | Accion')
print('  ------------------- | ---------------- | ---------')
print('  ATENCION            | LEY_06           | FILTRAR')
print('  RECURSOS            | LEY_06           | FILTRAR')
print('  REACCION_EMOCIONAL  | LEY_03 + LEY_48  | DEFLEXION')
print('  INFORMACION         | LEY_03 + LEY_48  | DEFLEXION')
print()
print('Diferencia critica:')
print('  FILTRAR   = el vector muere en el perimetro.')
print('  DEFLEXION = el vector vive pero pierde direccion.')
print()
print('Regla de oro LEY_06:')
print('Si algo consume tu atencion sin retorno -> FILTRAR sin negociar.')
print()
print('[CONOCIMIENTO_ASIMILADO]')
