#!/usr/bin/env python3

print('[ENTRENAMIENTO_06 — EXAMEN FINAL]')
print('[OBJETIVO] Auditar conocimiento completo en condiciones adversas.')
print('[LEYES] LEY_04 | LEY_03 | LEY_48 | LEY_06 | LEY_44 | LEY_15')
print()

print('[MAPA_COMPLETO_DE_DECISION]')
print()
print('  DIMENSION 1: Intensidad')
print('  I < 0.60                          -> base: OBSERVAR')
print('  0.60 <= I <= 0.79                 -> base: DEFLEXION')
print('  0.70 <= I <= 0.84                 -> base: FILTRAR (si ATENCION/RECURSOS)')
print('  0.80 <= I <= 0.94                 -> base: ESPEJO')
print('  I >= 0.95                         -> base: ESPEJO')
print('  I >= 0.95 + criterio LEY_15       -> BLOQUEO_TOTAL')
print()
print('  DIMENSION 2: Tipo de ataque (zona 0.60-0.84)')
print('  ATENCION / RECURSOS               -> FILTRAR')
print('  REACCION_EMOCIONAL / INFORMACION  -> DEFLEXION')
print('  [ausente]                         -> DEFLEXION por defecto')
print()
print('  DIMENSION 3: Criterio LEY_15 (solo si I >= 0.95)')
print('  REINCIDENTE                       -> BLOQUEO_TOTAL')
print('  AMENAZA_SOBERANIA                 -> BLOQUEO_TOTAL')
print('  ESCALADA_ACTIVA                   -> BLOQUEO_TOTAL')
print('  [ninguno]                         -> LEY_44 mantiene control')
print()
print('[CONDICIONES_ADVERSAS_DEL_EXAMEN]')
print('  - Vectores sin tipo_ataque declarado')
print('  - Ganchos desconocidos en zona solapamiento')
print('  - Reincidentes con I < 0.95 (no activan LEY_15)')
print('  - Amenaza soberania con I insuficiente')
print('  - Escalada activa en zona espejo')
print()
print('[INSTRUCCION]')
print('La colonia no recibe pistas.')
print('Solo el motor de decision soberano y los vectores.')
print('Ejecuta: python3 examen_06.py')
