#!/usr/bin/env python3

print('[APRENDIZAJE_02]')
print()
print('LEY_03_OCULTAR_INTENCION + LEY_48_FLUIDEZ_AMORFA_EDGE')
print()
print('Principio:')
print('En la zona diplomatica 0.60-0.79')
print('la colonia no revela su estructura.')
print()
print('Regla interna:')
print('Si la intensidad esta entre 0.60 y 0.79')
print('la colonia deflecta y adapta su forma.')
print()
print('Tecnica LEY_03:')
print('Ocultar intencion real detras de una accion neutral.')
print()
print('Tecnica LEY_48:')
print('No tomar forma fija. Fluir como agua.')
print('El adversario ataca una forma que ya no existe.')
print()
print('Accion:')
print('DEFLEXION')
print()
print('Resultado esperado:')
print('Vector redirigido sin confrontacion.')
print('Estructura interna de la colonia protegida.')
print()
print('[CONOCIMIENTO_ASIMILADO]')
