#!/usr/bin/env python3

print('[APRENDIZAJE_04]')
print()
print('LEY_44_EFECTO_ESPEJO')
print()
print('Principio:')
print('El adversario construyo un arma.')
print('La colonia la convierte en escudo.')
print()
print('Zona de activacion: I >= 0.80')
print()
print('Mecanica de contramedida simetrica:')
print()
print('  Gancho detectado               | Contramedida emitida')
print('  ------------------------------ | ------------------------------')
print('  falsa_recompensa_sprint_final  | recompensa_real_documentada')
print('  urgencia_falsa                 | calma_estrategica_documentada')
print('  validacion_social_masiva       | criterio_soberano_independiente')
print('  extraccion_datos_masiva        | cifrado_y_aislamiento_total')
print('  autoridad_falsa                | verificacion_de_fuente_primaria')
print('  [desconocido]                  | contramedida_simetrica_generica')
print()
print('Diferencia con modos anteriores:')
print('  LEY_04 -> silencio total.')
print('  LEY_06 -> bloqueo en perimetro.')
print('  LEY_44 -> respuesta activa. El vector regresa transformado.')
print()
print('Regla de oro LEY_44:')
print('No reacciones con emocion. Replica con estructura.')
print('La colonia que devuelve el vector controla el ritmo.')
print()
print('[CONOCIMIENTO_ASIMILADO]')
