#!/usr/bin/env python3

print('[APRENDIZAJE_05]')
print()
print('LEY_15_ANIQUILAR_AL_ENEMIGO')
print()
print('Principio:')
print('La colonia no destruye por impulso.')
print('Destruye por criterio.')
print()
print('Condicion de activacion:')
print('  I >= 0.95')
print('  + al menos uno de:')
print()
print('  Criterio           | Descripcion')
print('  ------------------ | ----------------------------------')
print('  REINCIDENTE        | El gancho ya fue procesado antes')
print('  AMENAZA_SOBERANIA  | Ataca identidad o firma CLHQ')
print('  ESCALADA_ACTIVA    | Adversario escalo tras recibir LEY_44')
print()
print('Sin criterio con I >= 0.95:')
print('  -> LEY_44 sigue activa. No se destruye lo desconocido.')
print()
print('Con criterio:')
print('  -> BLOQUEO_TOTAL. Canal destruido. Modo DEFINITIVO.')
print('  -> La colonia no registra mas senales de esa fuente.')
print()
print('Espectro completo consolidado:')
print()
print('  I < 0.60                        -> OBSERVAR')
print('  0.60-0.79 + REACCION/INFO       -> DEFLEXION')
print('  0.70-0.84 + ATENCION/RECURSOS   -> FILTRAR')
print('  0.80-0.94                        -> ESPEJO')
print('  >= 0.95 sin criterio             -> ESPEJO')
print('  >= 0.95 + criterio LEY_15        -> BLOQUEO_TOTAL')
print()
print('Regla de oro LEY_15:')
print('No todo enemigo merece ser aniquilado.')
print('Solo el que ya demostro que no puede ser redirigido.')
print()
print('[CONOCIMIENTO_ASIMILADO]')
